ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "oilIntervalKm" INTEGER;

CREATE TABLE IF NOT EXISTS "org_settings" (
  "orgId"         TEXT NOT NULL PRIMARY KEY,
  "oilIntervalKm" INTEGER NOT NULL DEFAULT 7000,
  "oilWarningKm"  INTEGER NOT NULL DEFAULT 500,
  "updatedAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
